# 数据库连接配置
spring.datasource.url=jdbc:mysql://101.34.212.211:3306/mint?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
spring.datasource.username=allen
spring.datasource.password=Allen@tx2025
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.allen.entity

# 启用404异常捕获
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
